### ISSUE TITLE
Able to leave the App

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#2]
When I first opened the app, I attempted to leave it. I pushed my Home Button on my Samsung Galaxy Tab and was presented with a window that said preform the following action with what?

One said something like Home Screen and the the other said On The Go Now...

I picked Home Screen and I can now get out of the app without the Mangers Pin. 

That is fine for me but not the ultimate End user. :-)

**Comment by jcaruso001** [comment]
I don't know if you remember this conversation but there will be some setup required by the company. They company will have to install the app and then when they set it up as you have instead of selecting "Home Screen" they will select "On the Go Now". What this means is that we're overriding the home screen button to go to our app.

**Comment by kev7040** [comment]
Oh - Sorry I don't remember, but that makes sense. :-) 
It did ask initially what default I wanted. 

I can make instructions to walk them through that. 

Thank You
