### ISSUE TITLE
Icon Re-design?

### ISSUE THREAD

**Issue by kev7040** [jcaruso001/On-The-Go-Now#3]
Is it Possible for us to re-design the home screen Icons?

They Just don't look that good on the big screen.

**Comment by jcaruso001** [comment]
What device are you looking at them on? I want to ensure it's not a sizing issue. However, if it's just because you don't like the look now that they are implemented we can re-design but I will have to charge again since the graphic's guy is going to charge me. 

Another option would be to roll it out as is and then later get your clients input on what they think would look good.

**Comment by kev7040** [comment]
I am viewing it on a Samsung Galaxy Tab 3 - the large tablet. 

I understand the extra charges - I fully expect that since I choose this current design. 

I think if we change the default background color to the gray color in the attached file it will look better?
At the moment I don't re-call how custom we got with the colors in the app... if the Background color is customize-ble by the customer - then we can forget changing the background color obviously. 
- 
![on the go now - in app icon - 14-11-14 2](https://cloud.githubusercontent.com/assets/10704592/5933444/655c85f2-a675-11e4-99a9-81d54ace8139.jpg)

**Comment by kev7040** [comment]
Never Mind Jason,

Sorry been working like crazy lately. Icon's good. I was just thinking about the background color.. Which I think I talked about in another issue on here.
Sorry.

**Comment by kev7040** [comment]
I do forget how custom we let the users get with the colors tho.

**Comment by jcaruso001** [comment]
as per our conversation we are going to close this ticket in lue of #6
